package gui.viewsandcontrollers.main;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class CalculadoraVistaController {
	@FXML
	private Button masButton;
	@FXML
	private Button entreButton;
	@FXML
	private Button porButton;
	@FXML
	private Button menosButton;
	@FXML
	private TextField txtNum1;
	@FXML
	private TextField txtNum2;
	@FXML
	private TextField txtResultado;

	// Event Listener on Button[#masButton].onAction
	@FXML
	public void sumar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#entreButton].onAction
	@FXML
	public void division(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#porButton].onAction
	@FXML
	public void multiplicar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#menosButton].onAction
	@FXML
	public void restar(ActionEvent event) {
		// TODO Autogenerated
	}
}
